export type TDistrict =
  | "bagerhat"
  | "bandarban"
  | "barisal"
  | "barguna"
  | "bhola"
  | "bogura"
  | "brahmanbaria"
  | "chapai nawabganj"
  | "chandpur"
  | "chattogram"
  | "chuadanga"
  | "cox's bazar"
  | "cumilla"
  | "dinajpur"
  | "dhaka"
  | "faridpur"
  | "feni"
  | "gaibandha"
  | "gazipur"
  | "gopalganj"
  | "habiganj"
  | "jamalpur"
  | "jashore"
  | "jhenaidah"
  | "jhalokathi"
  | "joypurhat"
  | "khagrachari"
  | "khulna"
  | "kishoreganj"
  | "kurigram"
  | "kushtia"
  | "lakshmipur"
  | "lalmonirhat"
  | "madaripur"
  | "magura"
  | "manikganj"
  | "meherpur"
  | "moulvibazar"
  | "munshiganj"
  | "mymensingh"
  | "naogaon"
  | "narail"
  | "narayanganj"
  | "narsingdi"
  | "natore"
  | "netrokona"
  | "nilphamari"
  | "noakhali"
  | "pabna"
  | "panchagarh"
  | "patuakhali"
  | "pirojpur"
  | "rajbari"
  | "rajshahi"
  | "rangamati"
  | "rangpur"
  | "satkhira"
  | "shariatpur"
  | "sherpur"
  | "sirajganj"
  | "sunamganj"
  | "sylhet"
  | "tangail"
  | "thakurgaon";

export type TGender = "male" | "female" | "other";
export type TBloodGroup =
  | "A+"
  | "A-"
  | "B+"
  | "B-"
  | "AB+"
  | "AB-"
  | "O+"
  | "O-";

export type TSubject =
  // Class 11-12 (HSC - Intermediate level)
  | "Physics"
  | "Mathematics"
  | "Higher Mathematics"
  | "Chemistry"
  | "Biology"
  | "Statistics"
  | "Logic"
  | "Sociology"
  | "Psychology"
  | "Islamic History"
  | "Islamic Studies"
  | "Computer Science"
  | "Bangla 1st Paper (HSC)"
  | "Bangla 2nd Paper (HSC)"
  | "English 1st Paper (HSC)"
  | "English 2nd Paper (HSC)"
  | "Accounting (HSC)"
  | "Management"
  | "Marketing"
  | "Finance, Banking & Insurance";
