import { TBloodGroup, TDistrict, TGender } from "./teacher.types";

export const Gender: TGender[] = ["male", "female", "other"];

export const BloodGroup: TBloodGroup[] = [
  "A+",
  "A-",
  "B+",
  "B-",
  "AB+",
  "AB-",
  "O+",
  "O-",
];

export const Districts: TDistrict[] = [
  "bagerhat",
  "bandarban",
  "barisal",
  "barguna",
  "bhola",
  "bogura",
  "brahmanbaria",
  "chapai nawabganj",
  "chandpur",
  "chattogram",
  "chuadanga",
  "cox's bazar",
  "cumilla",
  "dinajpur",
  "dhaka",
  "faridpur",
  "feni",
  "gaibandha",
  "gazipur",
  "gopalganj",
  "habiganj",
  "jamalpur",
  "jashore",
  "jhenaidah",
  "jhalokathi",
  "joypurhat",
  "khagrachari",
  "khulna",
  "kishoreganj",
  "kurigram",
  "kushtia",
  "lakshmipur",
  "lalmonirhat",
  "madaripur",
  "magura",
  "manikganj",
  "meherpur",
  "moulvibazar",
  "munshiganj",
  "mymensingh",
  "naogaon",
  "narail",
  "narayanganj",
  "narsingdi",
  "natore",
  "netrokona",
  "nilphamari",
  "noakhali",
  "pabna",
  "panchagarh",
  "patuakhali",
  "pirojpur",
  "rajbari",
  "rajshahi",
  "rangamati",
  "rangpur",
  "satkhira",
  "shariatpur",
  "sherpur",
  "sirajganj",
  "sunamganj",
  "sylhet",
  "tangail",
  "thakurgaon",
];

